version: '3.2'
services:
  nginx:
    image: nginx:1.17.8
    container_name: mynginx
    restart: always
    ports:
      - 80:80
      - 443:443
    protocol: tcp
    mode: host
    volumes:
      - /project/nginx/my-nginx.conf:/host/path/nginx.conf:ro
